name = "temp-mail-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "EMAIL_STORE"
id = "ddb43bdb69a942ff8d3622645754edb0"

[vars]
# Use a secret string here - must match the API_TOKEN in your frontend
API_AUTH_TOKEN = "kapil_secure_token_2026"